-- CreateTable
CREATE TABLE `WorkProgress` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `workItem` VARCHAR(255) NOT NULL,
    `description` TEXT NOT NULL,
    `category` ENUM('PLANNING', 'DESIGN', 'ENGINEERING', 'MARKETING', 'RESEARCH') NOT NULL DEFAULT 'PLANNING',
    `progress` ENUM('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'BLOCKED', 'BEHIND') NOT NULL DEFAULT 'NOT_STARTED',
    `priority` ENUM('CRITICAL', 'HIGH', 'MEDIUM', 'LOW') NOT NULL DEFAULT 'HIGH',
    `startDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `dueDate` DATETIME(3) NOT NULL,
    `notes` TEXT NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
